# Generated by Django 5.0 on 2023-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('airdrops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdrop',
            name='merkle_leaves',
            field=models.JSONField(default=dict, verbose_name='merkle_leaves'),
        ),
    ]
