# Generated by Django 5.0 on 2023-12-04 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True,
                                         db_index=True,
                                         verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True,
                                         db_index=True,
                                         verbose_name="updated at"),
                ),
                (
                    "address",
                    models.CharField(max_length=42,
                                     unique=True,
                                     verbose_name="address"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
